# Generated by Django 5.1.6 on 2025-03-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_covient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Covient',
        ),
    ]
