# Generated by Django 5.1.7 on 2025-04-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_covient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'Còn hàng'), ('out_stock', 'Hết hàng'), ('coming_soon', 'Sắp có')], default='in_stock', max_length=20),
        ),
    ]
