# Generated by Django 5.1.7 on 2025-05-13 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_author_product_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Chưa xác nhận'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao hàng'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('customer', 'order')},
        ),
    ]
